/* =========================================================
   Analysis & Validation Queries
   Purpose: Exploratory analysis and validation of reporting
   ========================================================= */

USE partner_reporting;

-- Sample data checks
SELECT * FROM sellers LIMIT 5;
SELECT * FROM orders LIMIT 20;
SELECT * FROM order_items LIMIT 5;
SELECT * FROM payments LIMIT 5;

-- Seller and transaction relationship
SELECT s.seller_id, s.seller_city, oi.price
FROM sellers s
JOIN order_items oi
ON s.seller_id = oi.seller_id
LIMIT 10;

-- Total revenue generated by each seller
SELECT s.seller_id, s.seller_city, SUM(oi.price) AS total_revenue
FROM sellers s
JOIN order_items oi
ON s.seller_id = oi.seller_id
GROUP BY s.seller_id, s.seller_city
ORDER BY total_revenue DESC
LIMIT 10;

-- Daily revenue trend
SELECT DATE(o.order_purchase_datetime) AS order_date, SUM(oi.price) AS daily_revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY DATE(o.order_purchase_datetime)
ORDER BY order_date
LIMIT 10;

-- Monthly revenue trend
SELECT DATE_FORMAT(o.order_purchase_datetime, '%Y-%m') AS order_month, SUM(oi.price) AS monthly_revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY DATE_FORMAT(o.order_purchase_datetime, '%Y-%m')
ORDER BY order_month;

-- Data Quality Checks

-- Orders without items
SELECT COUNT(o.order_id) AS orders_without_items
FROM orders o
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
WHERE oi.order_id IS NULL;

-- Orders without payment
SELECT COUNT(o.order_id) AS orders_without_payment
FROM orders o
LEFT JOIN payments p
ON o.order_id = p.order_id
WHERE p.order_id IS NULL;

-- Order items with missing seller reference
SELECT oi.order_id, oi.seller_id
FROM order_items oi
LEFT JOIN sellers s
ON oi.seller_id = s.seller_id
WHERE s.seller_id IS NULL
LIMIT 10;

-- Invalid price values
SELECT *
FROM order_items
WHERE price <= 0
LIMIT 10;

-- Dashboard validation queries
SELECT SUM(total_revenue) AS total_revenue_sql
FROM v_revenue_per_seller;

SELECT COUNT(*) AS orders_without_items_sql
FROM v_orders_without_items;
