-- =========================================================
-- Database: partner_reporting
-- Purpose: Reporting views for automated analytics
-- =========================================================


-- View: v_orders_clean
-- Purpose: Provide orders with standardized purchase datetime for reporting
CREATE VIEW v_orders_clean AS
SELECT order_id, order_status, order_purchase_datetime
FROM orders;

-- View: v_revenue_per_seller
-- Purpose: Calculate total revenue generated by each seller
CREATE VIEW v_revenue_per_seller AS
SELECT s.seller_id, s.seller_city, s.seller_state, SUM(oi.price) AS total_revenue
FROM sellers s JOIN order_items oi
ON s.seller_id = oi.seller_id
GROUP BY s.seller_id, s.seller_city, s.seller_state;

-- View: v_daily_revenue
-- Purpose: Aggregate revenue by day for time-series reporting
CREATE VIEW v_daily_revenue AS
SELECT DATE(o.order_purchase_datetime) AS order_date, SUM(oi.price) AS daily_revenue
FROM v_orders_clean o JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY DATE(o.order_purchase_datetime);

-- View: v_monthly_revenue
-- Purpose: Aggregate revenue by month for management reporting
CREATE VIEW v_monthly_revenue AS
SELECT DATE_FORMAT(o.order_purchase_datetime, '%Y-%m') AS order_month, SUM(oi.price) AS monthly_revenue
FROM v_orders_clean o JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY DATE_FORMAT(o.order_purchase_datetime, '%Y-%m');

-- View: v_orders_without_items
-- Purpose: Identify orders that do not have corresponding order items
CREATE VIEW v_orders_without_items AS 
SELECT o.order_id
FROM orders o LEFT JOIN order_items oi
ON o.order_id = oi.order_id
WHERE oi.order_id IS NULL;

-- View: v_orders_without_payment
-- Purpose: Identify orders with no payment records
CREATE VIEW v_orders_without_payment AS
SELECT o.order_id
FROM orders o LEFT JOIN payments p
ON o.order_id = p.order_id
WHERE p.order_id IS NULL;
